### ISSUE TITLE
Problem with too many active WebGL contexts

### ISSUE THREAD

**Issue by mgaonach** [uglymol/uglymol#11] opened 2023-02-07 11:27 UTC
I am having trouble while loading multiple instances of uglymol viewer in the same page. 

At some point while scrolling the page and loading more new viewers, I get a warning from the browser: 
```
WARNING: Too many active WebGL contexts. Oldest context will be lost.
```
It seems uglymol tries to handle this by calling a `state.reset` function which is missing: 
```
uglymol.js:5246 Uncaught TypeError: state.reset is not a function
    at resetGLState (uglymol.js:5246:1)
    at HTMLCanvasElement.onContextLost (uglymol.js:5359:1)
```

Is there any way to fix this issue or is there a hard limit to the number of viewers we can have?

Thanks for the help!

**Comment by wojdyr** [comment] 2023-02-13 18:36
A browser has a limit on the number of WebGL contexts and I [just read][1] that it's (usually?) 16.

It's been a couple years since I last changed anything in UglyMol, so I don't remember it well, but I see that I made a note about context loss in [TODO][2]. I think I never got to testing it. At least now we know it doesn't work.

If anyone know how it should be handled, I'd be happy to fix it.

[1]: https://stackoverflow.com/questions/59140439/allowing-more-webgl-contexts
[2]: https://github.com/uglymol/uglymol/blob/185b5fbb2eafc40e55805c6867e6a990c9180e96/TODO.md?plain=1#L2

**Comment by wojdyr** [comment] 2024-03-25 16:24
I checked it now and it seems that the limit of WebGL contexts has been increased, at least in Firefox. But the error could still be reproduced with:

    gl = V.renderer.context 
    gl.getExtension("WEBGL_lose_context").loseContext()

I fixed it, adding `state.reset()` and other functions that I removed by mistake.

Some pages that have multiple WebGL instances use a single WebGL context to render graphics for each canvas on a page, using drawImage() to copy what was rendered to the canvas for which it's intended. But this would make the viewer more complex, so I only fixed onContextLost().

**Closed by wojdyr** 2024-03-25 16:24 UTC
